### ISSUE TITLE
IP Range instead of singles IP option?

### ISSUE THREAD

**Issue by francisuk1989** [codeexpress/cidr2ip#1]
Excellent work but have a suggestion and that is to have an option to have the ip ranges like 
192.168.0.0-192.168.255.255 instead of been 192.168.0.0 192.168.0.1 192.168.0.2 etc

**Comment by codeexpress** [comment]
@francisuk1989 good suggestion. @alexandregv thanks for adding the option! This is on master now and the updated binaries are in the releases.
